// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/axliupore/judge/config"
	"github.com/axliupore/judge/internal/http"
	"github.com/axliupore/judge/internal/nsq"
	"github.com/axliupore/judge/internal/ws"
	"github.com/axliupore/judge/pkg/cache"
)

// Injectors from wire.go:

func InitializeApp(conf *config.Config, c *cache.Cache) (*App, func(), error) {
	http := &conf.Http
	server := provideHttpServer(http, c)
	ws := &conf.Ws
	wsServer := provideWsServer(ws, c)
	nsq := &conf.Nsq
	nsqServer := provideNsqServer(nsq, c)
	app := &App{
		Http: server,
		Ws:   wsServer,
		Nsq:  nsqServer,
	}
	return app, func() {
	}, nil
}

// wire.go:

func provideHttpServer(conf *config.Http, c *cache.Cache) *http.Server {
	return http.NewServer(conf, c)
}

func provideWsServer(conf *config.Ws, c *cache.Cache) *ws.Server {
	return ws.NewServer(conf, c)
}

func provideNsqServer(conf *config.Nsq, c *cache.Cache) *nsq.Server {
	return nsq.NewServer(conf, c)
}
